service: serverless-tracker

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs12.x
  environment:
    DB_URL: ${env:DB_URL}

plugins:
  - serverless-offline
  - serverless-plugin-warmup

functions:
  collect:
    handler: handler.collect
    events:
      - http:
          path: collect
          method: post
          cors: true
